name: "character_sheet"
description: "Achtung! Cthulhu 2d20 Character Sheet"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/baseAC2d20-1.jpg
    - lib/assets/baseAC2d20-2.jpg
    - lib/assets/baseAC2d20-3.jpg
